name: 'Compile Mermaid'

on:
  push:
    paths:
      - '**/*.mermaid'
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.mermaid'
      - '**/*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e '.*\.md$' -e '.*\.mermaid$' | xargs)"

    - name: mermaid files changed
      run: |
        echo ${{ steps.getfile.outputs.files }}

    - name: compile mermaid
      uses: neenjaw/compile-mermaid-markdown-action@master
      with:
        files: ${{ steps.getfile.outputs.files }}
        output: 'output'
      env:
        HIDE_CODEBLOCKS: 1

    - name: show changes
      run: |
        git status

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3.1.0
      with:
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        token: ${{ secrets.GITHUB_TOKEN }}
        signoff: false
        branch: example-patches
        commit-message: Add compiled mermaid
        title: '[MMDC] New mermaid files compiled'
        body: |
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: report, automated pr
        assignees: mermaid-bot
        reviewers: mermaid-bot
    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
